awk '
/^\.hero-actions \{/ {
    print ".hero-shapes {"
    print "  position: absolute;"
    print "  inset: 0;"
    print "  overflow: hidden;"
    print "  z-index: 5;"
    print "  pointer-events: none;"
    print "}"
    print ""
    print ".hero-shape {"
    print "  position: absolute;"
    print "  border-radius: 50%;"
    print "  filter: blur(80px);"
    print "  opacity: 0.4;"
    print "  animation: floatShape 8s ease-in-out infinite alternate;"
    print "}"
    print ""
    print ".shape-1 {"
    print "  width: 400px;"
    print "  height: 400px;"
    print "  background: var(--red);"
    print "  top: -100px;"
    print "  right: -100px;"
    print "}"
    print ""
    print ".shape-2 {"
    print "  width: 300px;"
    print "  height: 300px;"
    print "  background: var(--blue);"
    print "  bottom: 10%;"
    print "  left: 10%;"
    print "  animation-delay: -4s;"
    print "  animation-duration: 12s;"
    print "}"
    print ""
    print "@keyframes floatShape {"
    print "  0% { transform: translate(0, 0) scale(1); }"
    print "  50% { transform: translate(30px, -40px) scale(1.05); }"
    print "  100% { transform: translate(-20px, 20px) scale(0.95); }"
    print "}"
    print ""
}
{print}
' app/globals.css > app/globals_new.css && mv app/globals_new.css app/globals.css
